auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  instance_addr: loki
  path_prefix: /loki
  replication_factor: 1
  ring:
    instance_addr: loki
    kvstore:
      store: inmemory
  compactor:
    working_directory: /tmp/loki/compactor
    engine: v2
    retention_enabled: true
    retention_period: 336h
  storage_config:
    boltdb_shipper:
      active_index_directory: /tmp/loki/index
      cache_location: /tmp/loki/cache
      shared_store: filesystem
    filesystem:
      directory: /tmp/loki/chunks
  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 168h
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
