global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml # use the mounted path

scrape_configs:
  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:3000"]

  - job_name: "product-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["product-service:3001"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
